### ISSUE TITLE
Command Time out

### ISSUE THREAD

**Issue by ssugrim** [thoughtbot/cocaine#76]
Howdy, I was wondering how hard it would be to extend this library to include a timeout feature. When set it would raise an exception if a command took longer than the allotted amount of time (a parameter).

It would also need to detach or kill the subshell (not sure what the correct action is there, perhaps this should be a parameter too).

**Comment by jyurek** [comment]
I think a more flexible solution would be to have something else manage the timeouts, and wrap cocaine calls in that tool. Partly because timing things out is actually a more general problem, and partly because timing things out reliably in Ruby is surprisingly difficult. I'm not really interested in maintaining that in this library.
